name: Deploy Audio Files

on:
  push:
    branches:
      - main # Mude para o nome da sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Copiar arquivos de áudio
        run: cp -r audios/* /root/audios # pasta de saída do seu site no GitHub Pages

      - name: Commit e push os arquivos de áudio
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add root/audios
          git commit -m "Atualizar arquivos de áudio"
          git push
